apiVersion: v1
kind: Service
metadata:
  name: stackrox-alertmanager-webhook
  namespace: stackrox
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: stackrox-alertmanager-webhook
  type: ClusterIP